kind: pipeline
name: main

steps:
- name: build
  image: golang:1.11-alpine3.8
  commands:
  - go build main.go
  when:
    branch:
    - master
    event:
    - push

- name: run
  image: golang:1.11-alpine3.8
  commands:
  - go run main.go
  when:
    branch:
