kind: pipeline
name: default
workspace:
  base: /go
  path: "."
steps:
- name: test
  image: golang:latest
  commands:
    - go vet
    - go test -v -cover
- name: build
  image: golang:latest
  commands:
    - go build 
