kind: pipeline
name: default
workspace:
  base: /tmp
  path: "."

steps:
- name: test
  image: node
  commands:
  - npm install

- name: upload
  image: plugins/s3
  settings:
    bucket: code-deploy12345
    source: public/**/*
    target: /target/location
