kind: pipeline
name: default
workspace:
  base: /go
  path: "."
  
steps:
- name: test
  image: golang
  commands:
  - go test
  - go build

- name: publish
  image: plugins/docker
  settings:
    repo: octocat/hello-world
    tags: [ latest, 1.0, 1 ]


